version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: teamsync-db
    environment:
      POSTGRES_DB: teamsync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teamsync-network

  redis:
    image: redis:7-alpine
    container_name: teamsync-redis
    ports:
      - "6379:6379"
    networks:
      - teamsync-network

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: teamsync-server
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/teamsync
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - teamsync-network
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: teamsync-client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_SOCKET_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - teamsync-network
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  teamsync-network:
    driver: bridge