global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Microservices
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
    metrics_path: '/metrics'

  - job_name: 'project-service'
    static_configs:
      - targets: ['project-service:3002']
    metrics_path: '/metrics'

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:3003']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3004']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3005']
    metrics_path: '/metrics'

  # Infrastructure
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Custom application metrics
  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/custom-metrics'
    scrape_interval: 60s

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'api-gateway:8080'
        - 'user-service:3001'
        - 'project-service:3002'
        - 'task-service:3003'
    metrics_path: '/health'
    scrape_interval: 30s